-- HIVE
CREATE TABLE DW_BUYBOX.BBOX_LOG_AGR(
	  BOXAGR_EXTRACTION_DATE STRING
	, BOXAGR_BRAND_NAME STRING
	, BOXAGR_SELLERS_QTY INT
    , BOXAGR_PRODUCTS_QTY BIGINT
    , BOXAGR_XP_PRODUCTS_1P_3P BIGINT
    , BOXAGR_TOTAL_CASES BIGINT
    , BOXAGR_BBOX_1P_3P BIGINT
    , BOXAGR_BBOX_3P BIGINT
    , BOXAGR_1P_WINNER BIGINT
    , BOXAGR_3P_WINNER BIGINT
    , BOXAGR_1P_MIX_WINNER BIGINT
    , BOXAGR_3P_MIX_WINNER BIGINT
    , BOXAGR_1P_CHEAP_WINNER BIGINT       
    , BOXAGR_3P_CHEAP_WINNER BIGINT      
    , BOXAGR_CHEAP_WINNER BIGINT 
    , BOXAGR_RECORDS_QTY BIGINT
	)
	PARTITIONED BY (BOXAGR_EXTRACTION_DATE_P STRING)
	STORED AS PARQUET

ALTER TABLE BBOX_DIARY RENAME TO BBOX_LOG_AGR
ALTER TABLE BBOX_LOG_AGR CHANGE BOXAGR_EXTRACTION_DATE BOXAGR_EXTRACTION_DATE STRING