-- HIVE
CREATE TABLE DW_BUYBOX.BBOX_LOG_DIARY(
	  EXTRACTION_DATE STRING
	, BRAND_NAME STRING
    , DEPARTMENT STRING
    , BOXSEL_SELLER_ID STRING
    , BOXSEL_SCORE_RATING STRING
    , BOXAGR_PRODUCTS_QTY BIGINT
    , BOXSEL_RATING STRING
    , BOXSEL_TOTAL_CASES BIGINT
    , BOXSEL_TOTAL_WINNERS BIGINT
    , BOXSEL_1P_WINNER BIGINT
    , BOXSEL_3P_WINNER BIGINT
    , BOXSEL_LOW_PRICE BIGINT
    , BOXSEL_FIRST_AND_LOW_PRICE BIGINT
    , BOXAGR_1P_WINNER BIGINT
    , BOXAGR_3P_WINNER BIGINT
    , BOXAGR_1P_MIX_WINNER BIGINT
    , BOXAGR_3P_MIX_WINNER BIGINT
    , BOXAGR_BBOX_1P_3P BIGINT
    , RATING_UNDER_MINIMUM BIGINT
	)
	PARTITIONED BY (EXTRACTION_DATE_P STRING)
	STORED AS PARQUET