-- SELLER
CREATE TABLE DW_BUYBOX.BBOX_LOG_SELLER(
        BOXSEL_EXTRACTION_DATE STRING
       , BOXSEL_SELLER_ID STRING
       , BOXSEL_BRAND_NAME STRING
       , BOXSEL_LOW_PRICE INT
       , BOXSEL_FIRST_AND_LOW_PRICE INT
       , BOXSEL_QTY_PRODUCTS INT
       , BOXSEL_FIRST INT
       , BOXSEL_SECOND INT
       , BOXSEL_THIRD INT
       , BOXSEL_FOURTH INT
       , BOXSEL_FIFTH INT
       , BOXSEL_SIXTH INT
       , BOXSEL_SEVENTH INT
       , BOXSEL_EIGHT INT
       , BOXSEL_NINETH INT
       , BOXSEL_TENTH INT
       , BOXSEL_OTHERS INT
       , BOXSEL_TOTAL INT
)
PARTITIONED BY (BOXSEL_EXTRACTION_DATE_P STRING)
STORED AS PARQUET;
