-- DASHBOARD BUYBOX

SELECT API.*, MISPHR_ID_DEPT, MISPHR_DEPT, UPPER(CLIE_APELIDO) SELLERNAME
FROM LOGS_FRONT.LOG_BUYBOX_API API
LEFT OUTER JOIN CORE.MIS_PRODUCT_HIERARCHY MPH ON API.SKUID = MPH.MISPHR_ID_PRODUCT
LEFT OUTER JOIN DATALAKE_BOB.BOB_TERCEIRO_CIA BTC ON API.SELLERID = BTC.CLIE_ID_TERCEIRO
WHERE API.PARTITION_DATE = '2017-02-13'
AND API.LOAD_TICKET = 'A728CD65-4FBA-49A1-A832-6F7599F9F0A6'


SELECT
	API.DEPARTMENTID, 
	ISNULL(MPH.MISPHR_DEPT, 'NI')
FROM LOGS_FRONT.LOG_BUYBOX_API API
LEFT JOIN CORE.MIS_PRODUCT_HIERARCHY MPH 
ON API.SKUID = MPH.MISPHR_ID_PRODUCT
WHERE API.PARTITION_DATE = '2017-03-13'
GROUP BY 
    API.DEPARTMENTID, 
	MPH.MISPHR_DEPT
ORDER BY API.DEPARTMENTID

SELECT DISTINCT
	API.SELLERID
	, API.RATINGVALUE
    , API.PARTITION_DATE
FROM LOGS_FRONT.LOG_BUYBOX_API API
WHERE API.SELLERID = '7941752000104'
AND API.PARTITION_DATE = '2017-02-13'
LIMIT 100